### ISSUE TITLE
Cursor isn't visible when entering name or list name

### ISSUE THREAD

**Issue by mattrobmattrob** [SirArkimedes/listingbot#2]
Could just be a simulator only issue but it confused me at first. Textfield still accepts the text just no indication to user where the cursor is positioned.

Nothing typed:
![ios simulator screen shot aug 24 2015 10 09 17 pm](https://cloud.githubusercontent.com/assets/5728070/9459140/c98d89fa-4aac-11e5-8cd7-6c368c27cc7b.png)

Something typed:
![ios simulator screen shot aug 24 2015 10 10 02 pm](https://cloud.githubusercontent.com/assets/5728070/9459150/e84ec2c8-4aac-11e5-8741-dc9023db84b1.png)

**Comment by SirArkimedes** [comment]
Completed as of bc4833a8e076c032e703db53c47024b3c097018f
