### ISSUE TITLE
Animation of quantity for a list item is wonky

### ISSUE THREAD

**Issue by mattrobmattrob** [SirArkimedes/listingbot#4]
Animation of the "- 1 +" onto the screen looks super weird. Should probably take as long as the keyboard.

![ios simulator screen shot aug 24 2015 10 13 37 pm](https://cloud.githubusercontent.com/assets/5728070/9459181/80e99e9a-4aad-11e5-8d70-04c8fb9cfd28.png)

**Comment by SirArkimedes** [comment]
Agreed. Will fix.
