### ISSUE TITLE
Incorrect copy in list settings

### ISSUE THREAD

**Issue by mattrobmattrob** [SirArkimedes/listingbot#5]
Receipt should be recipient. Not sure if that's "final" copy or not though. May want to mention something about downloading the application too since that's required for the link to work.

![ios simulator screen shot aug 24 2015 10 17 44 pm](https://cloud.githubusercontent.com/assets/5728070/9459243/07192738-4aae-11e5-8999-5b3990ce914f.png)

**Comment by SirArkimedes** [comment]
Removed.
