### ISSUE TITLE
List "settings" icon is weird

### ISSUE THREAD

**Issue by mattrobmattrob** [SirArkimedes/listingbot#6]
I think there should be a share type icon and a trash can in place of the settings gear icon since the settings are share and delete. I can understand leaving it if you plan to add more functionality though (like a list of the participants unless that'll be accessed from the small text). This isn't really an issue and more of a suggestion.

**Comment by SirArkimedes** [comment]
I do plan to add more to it. I have those there for placeholders right now. I haven't much thought about the design of the settings menu, so they are just there for the function.
