### ISSUE TITLE
List shouldn't say "Congrats, I'm empty" when just created

### ISSUE THREAD

**Issue by mattrobmattrob** [SirArkimedes/listingbot#8]
Maybe?

![ios simulator screen shot sep 8 2015 8 42 33 pm](https://cloud.githubusercontent.com/assets/5728070/9752866/29e781fc-566a-11e5-88e8-568bba413876.png)

**Comment by SirArkimedes** [comment]
Right. Currently a placeholder. I'd like to add some sort of "empty state" image/animation rather than that text.
